# Configuration for Label Actions - https://github.com/dessant/label-actions

'Type: Support':
  comment: >
    :wave: @{issue-author}, we use the issue tracker exclusively
    for bug reports and feature requests. However, this issue appears
    to be a support request. Please hop over onto our [Discord](https://prowlarr.com/discord) 
    or [Subreddit](https://reddit.com/r/prowlarr)
  close: true

'Type: Indexer Request':
  comment: >
    :wave: @{issue-author}, we use the issue tracker exclusively
    for bug reports and feature requests. However, this issue appears
    to be a indexer request. Please use our Indexer request [site](https://requests.prowlarr.com/)
  close: true