---
name: Indexer Sync Automation

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      force_sync:
        description: 'Force sync even if up to date'
        required: false
        default: false
        type: boolean
      debug_mode:
        description: 'Enable debug logging'
        required: false
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-indexers:
    name: Sync Indexers from Jackett
    runs-on: ubuntu-latest
    if: github.repository == 'Prowlarr/Indexers'
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Create virtual environment and install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run indexer sync
        run: |
          # Run the sync script with -z mode, automation mode, and push enabled
          if [ "${{ github.event.inputs.debug_mode }}" = "true" ]; then
            ./scripts/indexer-sync-v2.sh -z -a -p -b automated-indexer-sync -o origin -m dev
          else
            ./scripts/indexer-sync-v2.sh -z -a -p -b automated-indexer-sync -o origin
          fi

      - name: Summary
        run: |
          echo "✅ Indexer sync workflow completed"
          echo "📝 Changes pushed to automated-indexer-sync branch"
          echo "🔗 PR creation moved to separate workflow (currently on ice)"